### ISSUE TITLE
"Update not possible" error message

### ISSUE THREAD

**Issue by CookieShade** [TheDoctor0/CSCOInstaller#2]
When starting the program, the message "UPDATE NOT POSSIBLE!" is shown, and the progress bar does not fill. This happened both before and after a previous version (1.1d) was deleted. Because of this, the installer can't download or install the mod. Trying an earlier build of the installer, 1.43, the program does not even start, and reports a System.FormatException followed by an APPCRASH event in Windows Problem Reports.
The program window looks like this (build 1.5):
![image](https://user-images.githubusercontent.com/17798152/38778965-be4a3242-40c1-11e8-8e24-6d22190aa425.png)

**Comment by TheDoctor0** [comment]
The old version of the installer is not working anymore, because there have been pretty huge changed to version check mechanism and it's not backward compatible.

Previously there were 3 active (mine included) download links for an installer to use, so if one or even two of them stopped working it was still possible to get the mod.
Sadly, now 1.2t HF2 (1.2 for short) version is only hosted by me on my VPS (https://cs-reload.pl/csco/ClassicOffensive.zip) along my forum.

This site is guarded by CloudFlare and I assume that it's firewall blocked request checking if the file is still available to download. I changed firewall settings, so you can try it now.
